### ISSUE TITLE
TR (Türkiye) located server still have "Pirate" flag.

### ISSUE THREAD

**Issue by xXerM** [fpaezf/CS2-RCON-Tool-V2#11]
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/52131051/f34de08e-bf0f-4c10-8530-8621e12cf1df)

**Comment by fpaezf** [comment]
Are you using v0.8a?. If not, please update. Best regards.

**Comment by xXerM** [comment]
I'm using v0.8a

**Comment by fpaezf** [comment]
I will do some tests, thanks for the feedback.

**Comment by fpaezf** [comment]
Change sducs.giize.com to 159.146.68.105 while i look for a workarround. Best regards.

**Comment by fpaezf** [comment]
Fixed. Please update.
https://github.com/fpaezf/CS2-RCON-Tool-V2/releases/tag/v0.9a

**Comment by xXerM** [comment]
Updated. Thank you so much, now it is properly show the flag no matter if its numeric or domain
