### ISSUE TITLE
2 Local cs2 server?

### ISSUE THREAD

**Issue by Tripl389** [fpaezf/CS2-RCON-Tool-V2#12]
Hey...
I have created two CS2 servers on my computer and would like to manage them using your tool. However, I have no idea how to display them in the tool or what settings I need to configure. Can you provide a step-by-step guide? Should the server already be running, or can I start it through the tool? So many questions...

**Comment by fpaezf** [comment]
Manage servers -> Add server

**Name:** Whatever to identify the server like **Deathmatch server**
**Host/IP:** Your local ip (https://www.whatismybrowser.com/detect/what-is-my-local-ip-address#windows)
**Port:** The port you setup in the game server (normally 27015)
**Password:** Your rcon password (put **rcon_password "yourpassword"** cvar in server.cfg)

Can I start it through the tool? -> NO, to manage server installation please use my other tool: https://github.com/fpaezf/CS2-server-manager

**Comment by Tripl389** [comment]
@fpaezf 

Hello,
I took some screenshots. So, in cs2.exe path, I enter the path of the game, not the server. I tried to add the servers through the manager, but unfortunately, I always get an error. You can see it in the screenshots. Can you help me? Both servers are running as well.

![Screenshot 2023-12-09 131548](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/146624106/21675a4c-17e5-46d0-abce-f27ceffda4de)
![Screenshot 2023-12-09 131620](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/146624106/9a40c88a-1c84-48ef-bf46-11a6921f2723)
![Screenshot 2023-12-09 131916](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/146624106/00f7a1cf-4499-4735-a6fe-57e1fcb59bd2)
![Screenshot 2023-12-09 132050](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/146624106/b1e0217d-33b8-402c-8401-127ab6dfefeb)
![Screenshot 2023-12-09 132601](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/146624106/61f96752-8b60-43bc-91a1-14acecda37e6)
![Screenshot 2023-12-09 133116](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/146624106/5a05883c-5595-4819-a7b8-27158c4f60fc)
