### ISSUE TITLE
Error while adding workshop map [v0.9a]

### ISSUE THREAD

**Issue by xXerM** [fpaezf/CS2-RCON-Tool-V2#13]
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/52131051/80cb930c-b104-4f2e-8db6-b5b07be395fc)

**Error while adding data to Servers.xml file. 
Object reference not set to an instance of an object**

**Comment by fpaezf** [comment]
Can you send me your servers.xml file to reproduce the error?. Edit with notepad and change rcon password or change it after send me the file. Thanks in advance.

**Comment by fpaezf** [comment]
In the application settings window there's an option to reset the Servers.xml file, remember that this action will delete all your server list data.

**Comment by xXerM** [comment]
I'll check then send you feedback

**Comment by fpaezf** [comment]
Did you manually edit the file?, maybe you accidentally deleted a <> key?

**Comment by xXerM** [comment]
I did not edit Servers.xml but did reset now I'll try again and send you Servers.xml

**Comment by xXerM** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Servers>
  <Server>
    <Name>SDU ESPORTS</Name>
    <IP>sducs.giize.com</IP>
    <Port>27015</Port>
    <Password>********</Password>
    <WSMaps>
      <Map>
        <ID>3077755321</ID>
        <Name>aim_redline_bb</Name>
      </Map>
    </WSMaps>
  </Server>
</Servers>

**Comment by fpaezf** [comment]
Use pastebin

**Comment by xXerM** [comment]
https://pastebin.pl/view/d26c5016

**Comment by fpaezf** [comment]
Xml seems ok.

**Comment by xXerM** [comment]
Yes I checked also and did not see anything

**Comment by fpaezf** [comment]
Error appears on map adding/editing/loading/changing?

**Comment by xXerM** [comment]
Adding.

![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/52131051/cae6daac-1d0f-471a-8abe-d3cee1b6ca85)
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/52131051/927ecafb-a308-48a4-a076-676fee73b15d)
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/52131051/d4cad2bf-5bba-4f20-8d92-9ad531f4bdb8)

**Comment by fpaezf** [comment]
Ok, i think i know what's happening, i will fix it in the next update. Sorry for the unconvenience.

**Comment by xXerM** [comment]
**Waiting for next update, appreciate your work. 
Thanks in advance.**

**Comment by fpaezf** [comment]
Done, reset Servers.xml file, now should work.
Let me know any inconvenience.
Best regards.
