### ISSUE TITLE
Error Loading server list file. Conversion from string "Err" to type 'Integer' is not valid.

### ISSUE THREAD

**Issue by stillnocake** [fpaezf/CS2-RCON-Tool-V2#14]
Hello,

I've been trying to use the CS2-RCON-Tool-V2 and encountered an error that consistently appears. I thought it would be best to report this issue to help improve the tool.

Issue Description:

**Error:** Error Loading server list file. Conversion from string "Err" to type 'Integer' is not valid.
**Steps to Reproduce:** Setup the location for the cs2.exe binary.  This message pops up everytime I launch the tool.
**Expected Behavior:** No error message
**Actual Behavior:** The message appears, then the application crashes and ask if I would like to continue. When I press continue, the same error message comes back.
**Environment:** Windows 10, dedicated server running on a docker container (the rcon password is correctly set up and the server can be connected to)

I hope this information helps
 in diagnosing and resolving the issue. I appreciate the effort put into developing this tool and look forward to using it without this error.

Thank you for your hard work and dedication to this project.

Best regards,
stillnocake

![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/56047361/7c72f0aa-7e6d-480d-83be-adf7fbc82f63)

**Comment by fpaezf** [comment]
Hi, thanks for the feedback. What's the server ip/port to reproduce the error?

**Comment by stillnocake** [comment]
Its a lan-only server for now.. so [LAN_IP]:27015. 
Thank you !

**Comment by fpaezf** [comment]
Ok, the fix will be released in 1-2 hours.

**Comment by stillnocake** [comment]
Heres the server.xml file:
<?xml version="1.0" encoding="utf-8"?>
<Servers>
  <Server>
    <Name>sncloc</Name>
    <IP>192.168.X.X</IP>
    <Port>27015</Port>
    <Password>nottheactualpassword</Password>
    <WSMaps>
      <Map>
        <ID>3077755321</ID>
        <Name>aim_redline_bb</Name>
      </Map>
      <Map>
        <ID>3082605693</ID>
        <Name>aim_dust_1v1</Name>
      </Map>
    </WSMaps>
  </Server>
</Servers>

**Comment by stillnocake** [comment]
Here is the server.xml file:
`<?xml version="1.0" encoding="utf-8"?>
<Servers>
  <Server>
    <Name>localcs2</Name>
    <IP>192.168.X.X</IP>
    <Port>27015</Port>
    <Password>notthepassword</Password>
    <WSMaps>
      <Map>
        <ID>3077755321</ID>
        <Name>aim_redline_bb</Name>
      </Map>
      <Map>
        <ID>3082605693</ID>
        <Name>aim_dust_1v1</Name>
      </Map>
    </WSMaps>
  </Server>
</Servers>`

**Comment by fpaezf** [comment]
Fixed, please update.
https://github.com/fpaezf/CS2-RCON-Tool-V2/releases/tag/v1.1b
