### ISSUE TITLE
The tool version in 1.1b is 1.0b ?

### ISSUE THREAD

**Issue by stillnocake** [fpaezf/CS2-RCON-Tool-V2#15]
Hello again, 
I think that you may have forgotten to increase the version value because versionn 1.0b is displayed and I get the 'OOPSIE' sound even thought the version has been upgraded.
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/56047361/2f4376b1-df88-445a-a200-f77969abcbea)

Delete this post if I'm incorrect.

Thank you !

**Comment by fpaezf** [comment]
Forgot to change version number, i'm coding, eating and talking on the phone, sorry for that.
Uploaded the fixed one: https://github.com/fpaezf/CS2-RCON-Tool-V2/releases/tag/v1.1b

**Comment by fpaezf** [comment]
Errors are fixed with this version?

**Comment by stillnocake** [comment]
I can confirm that the version bug has been fixed !

But there is a .zip in the zip ??
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/56047361/0f1c4ca3-939d-4711-a1e3-5cc8ad1ec1c5)

**Comment by fpaezf** [comment]
Oh my god... fixed.
