### ISSUE TITLE
Error: Host not reachable!

### ISSUE THREAD

**Issue by Tripl389** [fpaezf/CS2-RCON-Tool-V2#16]
Hello,

This version works better than the previous one. Unfortunately, I still have the problem that the error "Error: Host not reachable!" appears. How can I fix this? The servers are running on my local computer.

![Screenshot 2023-12-11 232042](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/146624106/902d6e31-1a21-460c-9f3a-4ea1a00b4974)

Would be great if you could help me. Thank you

**Comment by fpaezf** [comment]
Can you share the startup command line?
Are you using Docker?
Try to use ports 27015 for server 1 and 28015 for server 2

**Comment by Tripl389** [comment]
Command line : -dedicated -port 27015 +sv_setsteamaccount 3B7C489C85732XXXXXXXXXXXXC052697 +map de_inferno +exec server.cfg -autoupdate -maxplayers 12 -authkey 4055B322E09XXXXXXXXXXXX80CEE4E67 +game_alias custom

No Docker. Its a Windows Maschine

When i start only 1 Server on Port 27015. Its the same error as i start 2 Server.

**Comment by fpaezf** [comment]
Try this:

-dedicated -usercon -console -secure +game_type 3 +game_mode 0 +map de_inferno +exec server.cfg -ip 123.123.123.123 -port 27015 -maxplayers 12 +sv_setsteamaccount "3B7C489C85732XXXXXXXXXXXXC052697"

-autoupdate -game_alias and -authkey i think does nothing.

Try with -ip YOURLOCALIP and if it not works try -ip YOUREXTERNALIP or -ip 0.0.0.0

**Comment by Tripl389** [comment]
That helped! 
I had to enter LOCALIP or 0.0.0.0 in the command line. 
In the GameServer Manager only the LOCALIP works.

Now it works great.

**Comment by fpaezf** [comment]
If you open the ports in the router (TCP/UDP) you can use EXTERNALIP in the rcon tool, if you can't reach it, your ports are not correctly forwarded.
