### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Eplexx** [fpaezf/CS2-RCON-Tool-V2#17]
Any idea why it fails to connect to the server? Everything seems to work fine for me and my friends, but the software cannot connect to my server.

Im a noice in this, but I think everything is alright from my servers perspective

![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/153734588/31b63ff4-d2ed-46d4-b747-d721756a2294)

Am I missing something?

![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/153734588/19dc4cf6-b7d6-4d45-b7ac-ddaf8e3ae90f)

**Comment by fpaezf** [comment]
To join a server, the tool will call a simple process.start method in the form of:

steam://connect/ip:port

I can see some users blaming about steam failing to join servers for CS2, ARK and other games.

It's a Steam error and Valve has to fix it, it's not a tool bug.

Try to replace ip and port on the Steam link with your data and paste the link in Chrome or other web browser to test if it works.

**Comment by Eplexx** [comment]
What can I do then? If I use local IP, the server manager don't find it.

**Comment by Eplexx** [comment]
Nvm, thanks alot - it seems to work with local IP now - cheers!

**Comment by fpaezf** [comment]
> Nvm, thanks alot - it seems to work with local IP now - cheers!

Good!, anyway i will try to look for a fix.

Thank you for the feedback.
