### ISSUE TITLE
No connection possible - port 28015

### ISSUE THREAD

**Issue by freeze2404** [fpaezf/CS2-RCON-Tool-V2#18]
Connection to CS2 server is not working.
I can add the server, but then the tool gets stuck at "reading hostname data".
Old RCON Tool works perfectly.
Maybe the issue appears due to the fact that I'm not using the standard port 27015, but 28015?
Feel free to contact me to get the credentials.

**Comment by fpaezf** [comment]
ip:port?
Are you using docker?
Linux or windows server?

**Comment by freeze2404** [comment]
My mistake, used wrong password 😅

**Comment by freeze2404** [comment]
Just as a proposal: It would be nice if the tool would tell, that there is an authentication issue instead of just freezing / getting stuck. Maybe this would be possible? :)
