### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ghostt187** [fpaezf/CS2-RCON-Tool-V2#21]
After adding server the program crashes or even if the server is added and i try to refresh it crashes

**Comment by fpaezf** [comment]
Hi, thank you for your feedback.

Wich version of the application are you using?.

Server ip:port?

Error message?

**Comment by ghostt187** [comment]
Latest version
95.214.180.196:27015
No error message just as soon as i open the program it stops respodning

**Comment by fpaezf** [comment]
I have done some tests and i haven't any problem with your server, all works fine. Go to application folder and delete all .ini and all .xml files, then restart the application and add again the server. Let me know if it fixes the issue.

Make sure you've downloaded the latest version v1.3b: https://github.com/fpaezf/CS2-RCON-Tool-V2/releases/tag/v1.3b

**Comment by ghostt187** [comment]
![1](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/147412694/9022e011-a443-460c-b353-ea2cbac58ce3)
same thing again

**Comment by ghostt187** [comment]
and btw that flag is wrong shoudnt it be germany flag since the server is located in germany?

**Comment by fpaezf** [comment]
> ![1](https://private-user-images.githubusercontent.com/147412694/293984179-9022e011-a443-460c-b353-ea2cbac58ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTc4MDcsIm5iZiI6MTcwNDMxNzUwNywicGF0aCI6Ii8xNDc0MTI2OTQvMjkzOTg0MTc5LTkwMjJlMDExLWE0NDMtNDYwYy1iMzUzLWVhMmNiYWM1OGNlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMTMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzI2NzU2ZWY0YzQ2NTRmNDM1NmEyZGU5ZGNlZDlhMjFlYTc0MzNlZTJhNGFmYzdkMjgwNGY5MWM4MWVmZDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8kjUvsMJpqjbJlIzS-CV9uv_YN1MRQLCAY4TyWM4nYg) same thing again

Delete 0.0.0.0 server and try again.

**Comment by fpaezf** [comment]
> and btw that flag is wrong shoudnt it be germany flag since the server is located in germany?

It appears as germany ip server on my application:
![Sin título](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/28062918/3dd2a33e-e6b5-4ed8-a7d2-1faa475ae2c5)

**Comment by ghostt187** [comment]
> > ![1](https://private-user-images.githubusercontent.com/147412694/293984179-9022e011-a443-460c-b353-ea2cbac58ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTc4MDcsIm5iZiI6MTcwNDMxNzUwNywicGF0aCI6Ii8xNDc0MTI2OTQvMjkzOTg0MTc5LTkwMjJlMDExLWE0NDMtNDYwYy1iMzUzLWVhMmNiYWM1OGNlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QyMTMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzI2NzU2ZWY0YzQ2NTRmNDM1NmEyZGU5ZGNlZDlhMjFlYTc0MzNlZTJhNGFmYzdkMjgwNGY5MWM4MWVmZDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8kjUvsMJpqjbJlIzS-CV9uv_YN1MRQLCAY4TyWM4nYg) same thing again
> 
> Delete 0.0.0.0 server and try again.

yes i did that and same thing

**Comment by fpaezf** [comment]
Maybe the firewall is blocking the application?

**Comment by ghostt187** [comment]
@fpaezf sorry for no replying no i dont think its firewall cuz other programs like hlsw or sourceadmintool are working fine

**Comment by fpaezf** [comment]
Open Settings.xml and change:

< DataFetchMode>Rcon< /DataFetchMode >

to

< DataFetchMode>A2S< /DataFetchMode >

Let me know if this unlocks the GUI.

**Comment by ghostt187** [comment]
> Open Settings.xml and change:
> 
> < DataFetchMode>Rcon< /DataFetchMode >
> 
> to
> 
> < DataFetchMode>A2S< /DataFetchMode >
> 
> Let me know if this unlocks the GUI.

yes that fixed it thanks

**Comment by fpaezf** [comment]
A2S is not fully implemented by Valve, player names and country flags will not work. Anyway, can you provide the XML files in your installation folder in order to test and try to replicate and debug the error?. 

You can change the rcon password later, i promise to not manipulate your server in any way.

Thank you!

**Comment by ghostt187** [comment]
do u have discord where u can contact u

**Comment by fpaezf** [comment]
fpaez_75043
