### ISSUE TITLE
Ban greyed out

### ISSUE THREAD

**Issue by Rurd2di** [fpaezf/CS2-RCON-Tool-V2#22]
For some reason ban for 1 hour and per is greyed out.
everything else is fine
![bug](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/19353599/1ee6a8df-11a7-48b9-8bff-1615e61f387e)

**Comment by fpaezf** [comment]
Ban commands still not works on CS2, only kick.

Best regards.
