### ISSUE TITLE
Please add a Linux version?

### ISSUE THREAD

**Issue by Pdam67** [fpaezf/CS2-RCON-Tool-V2#23]
Are you familiar with programming in linux, because making a port to linux would really be a help for me.

Although it's your program and you can do what you want with it, would it be possible to make my own linux port?

**Comment by fpaezf** [comment]
Hi, thanks for your feedback.

I have no plans to create a Linux version but you can use the info about protocols i've published on Github to create your own version.

https://github.com/fpaezf/vb.net-a2s_Info
https://github.com/fpaezf/vb.net-a2s_Player
https://github.com/fpaezf/Valve-RCON-protocol-in-VB.NET

Best regards.
