### ISSUE TITLE
Feature request ( not an issue! )

### ISSUE THREAD

**Issue by Jano1959** [fpaezf/CS2-RCON-Tool-V2#25]
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/46221921/00162867-26c6-4a74-aef4-a3a421d4cf09)

Would be fantastic if in the "Scheduled Tasks" could be a manuel "fire" option. 

That way, we could easy fire of a command string to set the server for whatever we need, I often use this in RCON when testing settings etc.

mp_maxrounds 2; mp_warmuptime 5; mp_halftime_duration 1; mp_buytime 30; mp_roundtime 1; mp_maxmoney 64000; mp_startmoney 32000; mp_restartgame 5; say "LIVE!!"

Would be super nice for some function where we could run these custom commands someway.

**Comment by fpaezf** [comment]
Hi, thanks for the feedback.

Is adding a right-click option a good choice for you?

![Sin título](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/28062918/dcc42be2-154c-48c4-a052-dceb823eae54)

**Comment by Jano1959** [comment]
Wow that would be supernice, but without it having to be run on a day/time or the need to enable/disable it.. I know it kinda defy the "Scheduled Task".
But it could be very useful :)
