### ISSUE TITLE
Error connecting to CS2 servers

### ISSUE THREAD

**Issue by BizSAR** [fpaezf/CS2-RCON-Tool-V2#26]
Using RCON data fetching, the _basic server details are loading_, but when selecting a given server, the tool hangs a bit and then gets the error: "Error connecting to server". I've set the proper IP, port, and RCON password in the tool.

Using the A2S UDP data fetching mode, I get the error "...connection attempt failed because the connected party did not properly respond after a perio...". 

I prefer to use the RCON method so I can admin the players, etc.

I'm running multiple CS2 servers on different ports, running on Win10Pro, and the firewall is disabled on the server system. On the remote system where the tool is running, I have the tool allowed through the Windows firewall. All IPs are on the same subnet.

I get the same errors when running the tool on the server system itself too.
All servers are up-to-date.

**Comment by fpaezf** [comment]
Hi, thanks for the feedback.
Seems to be a server side connection problem not an application bug.

Check open ports, server cfg, firewall, etc...

**Comment by ParadoxLeon** [comment]
I had the same issue.

The server was running on a different port than `27015` changed it back and it worked for some reason. 
The ports were open but still no luck also when using `127.0.0.1` as IP this error occurs for me.

**Comment by fpaezf** [comment]
Use local ip not 127.0.0.1. If port fails, check if it's open for tcp and udp.
