### ISSUE TITLE
Pls remove autoriderect to git when closing "New update" window

### ISSUE THREAD

**Issue by abiba-zabbix** [fpaezf/CS2-RCON-Tool-V2#27]
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/128633387/7c48550c-bdad-42f2-9ba8-ec9d86c228bc)
Its super annoying, pls remove this auto link open to git. I would suggest add additional button like "Go to git" or something like that but every time when i open the application i cant just skip it and it redirect to git anyway - press X on window or OK >_<

**Comment by fpaezf** [comment]
Dude, just update the application, it's easy...
