### ISSUE TITLE
Wanna Collab ?

### ISSUE THREAD

**Issue by Izocel** [fpaezf/CS2-RCON-Tool-V2#4]
Offering myself as collaborator for v2  ;)

**Comment by fpaezf** [comment]
Sure!, i write you if i need help!

**Comment by fpaezf** [comment]
Still want to help?: https://github.com/fpaezf/CS2-RCON-Tool-V2/issues/1

**Comment by Izocel** [comment]
> Still want to help?: https://github.com/fpaezf/CS2-RCON-Tool-V2/issues/1

Yeah sure

**Comment by fpaezf** [comment]
Please check this issue, let me know if you can review the Rcon.dll source code to fix the error: https://github.com/fpaezf/CS2-RCON-Tool-V2/issues/1

**Comment by Izocel** [comment]
The issue is on another repo the other guys will check this.

**Comment by fpaezf** [comment]
Wich repo?
