### ISSUE TITLE
GameServer++ crashing after first server saved

### ISSUE THREAD

**Issue by 0aShadow** [fpaezf/CS2-RCON-Tool-V2#5]
When I try to save my server to the "Manage servers" list, the tool crashes immediately after saving the adress, name and password.
All informations provided to the tool are correct.

I already deleted the old files: 
Schedule.xml
Servers.xml
Settings.xml

Screenshot:
![image](https://github.com/fpaezf/CS2-RCON-Tool-V2/assets/135456420/7f9c6751-2c9b-4922-82ce-42700996dd9c)
If you wonder it says "Not responding" on german

Do you need further informations or something else to work with?

**Comment by fpaezf** [comment]
I see, will be fixed in the next update. Meanwhile, close the application and edit manually the servers.xml file with notepad filling your server data, then restart the application, this is a temporal workarround while i fix the bug. Thanks for the feedback!.

**Comment by fpaezf** [comment]
Fixed
