### ISSUE TITLE
Missing country flag in server list

### ISSUE THREAD

**Issue by fpaezf** [fpaezf/CS2-RCON-Tool-V2#6]
If your server's country flag not shows correctly, please write a comment with the following data:

- Server **IP/HOST:PORT** (Ex: _123.123.123.123:27015_ or _my.gameserver.com:27015_)
- Server location country (Ex: _Spain_ or _Canada_)
- Server location country **ISO Alpha-2** code (https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)

Thanks for your feedback!

**Comment by fpaezf** [comment]
Türkiye flag was added.

**Comment by fpaezf** [comment]
Added +20 country flags.

**Comment by fpaezf** [comment]
Added +8 country flags

**Comment by fpaezf** [comment]
Added + 6 country flags

**Comment by fpaezf** [comment]
Added +12 country flags

**Comment by fpaezf** [comment]
Added 4 new country flags

**Comment by daniel-gramos** [comment]
Server IP/HOST:PORT servidor.arenarapidfire.com.br:27015
Server location country: Brazil
Server location country ISO Alpha-2 code: ISO 3166-2:BR

**Comment by fpaezf** [comment]
Brazil is handled by the software, i will update geolite database in the next release
