### ISSUE TITLE
I tried to download source code but is missing

### ISSUE THREAD

**Issue by horvathzeros** [fpaezf/CS2-RCON-Tool-V2#7]
Hi, i tried to download as ZIP the proyect but there is not any kind of source code

Gracias por el curro, se echa de menos algo como el HLSW xD

**Comment by fpaezf** [comment]
Hola!, por el momento no voy a publicar el código fuente pero vamos, que solo es una interfaz, el motor del programa es una versión recortada de esta librería: https://github.com/untodesu/rcon-dotnet

De hecho, podrías descompilar el programa con ILDasm o algún otro descompilador de .NET y ver cómo funciona por dentro o incluso extraer el código fuente para hacer tu propia versión ya que el ejecutable no está protegido de ningún modo.

Muchas gracias por tu apoyo!, en la próxima versión se podrán especificar comandos de Metamod y CounterStrikeSharp para ejecutarlos con solo un click, el programa te avisará para actualizar.

Saludos!
